-- ============================================================
-- Betting — fake-currency wagers on scheduled matches.
--
-- The house is the admin, same as everywhere else in this app: an
-- admin opens a market on a scheduled match with odds they pick
-- (there is no Elo or rating math anywhere in this file — the whole
-- point is that the house sets a line the way a real bookmaker
-- would, and the "favourite" is whoever the admin decided deserves
-- the shorter price), players and spectators bet fake FC against
-- that price, the admin accepts or rejects each bet before it's
-- live, and once the real match is played the admin enters the
-- actual result and every accepted bet resolves itself.
--
-- Three bet types, same market, increasing risk:
--   winner      — pick who wins.                    pays odds_p1/odds_p2 straight
--   margin      — pick who wins AND the set margin.  pays that price × margin_multiplier
--   exact_score — pick who wins AND every set score. pays that price × exact_multiplier
-- The multipliers are the "riskier bets pay more" knob, set per
-- market by whoever opens it; the odds are the "favourites pay less"
-- knob, also set by the admin, not derived from anything.
--
-- Everyone starts with 300 FC the first time they pick a name (see
-- ensure_wallet() below, called from the app right after a display
-- name is chosen or a roster profile is claimed).
--
-- Run this in the Supabase SQL editor, on its own (Supabase runs a tab
-- as one transaction, so pasting it alongside anything else risks the
-- whole paste rolling back on an unrelated error). Idempotent.
--
-- Needs public.is_admin() (run admin-security.sql first, same
-- requirement as site-config.sql and live-drafts.sql) and the
-- scheduled_matches table that backs the Ladder's scheduled-match
-- broadcasts — both already part of this deployment if admin login
-- and "Schedule a match" work today.
-- ============================================================

-- ============================================================
-- wallets — one row per player name. Balance is never written by
-- the client directly: every table below has select-only RLS for
-- everyone and no insert/update/delete policy at all, so the anon
-- key literally cannot move FC around except through the
-- SECURITY DEFINER functions further down, each of which re-checks
-- everything server-side. That's the actual ledger integrity; the
-- app's own balance checks are just UX.
-- ============================================================

create table if not exists public.wallets (
  name_key    text primary key,             -- lower(trim(name)) — stable identity key
  name        text not null,                -- last-seen display casing, for showing on screen
  balance     integer not null default 300 check (balance >= 0),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table public.wallets is
  'Fake-currency balances, keyed by lower(trim(player name)). Starts every new '
  'name at 300 FC. Written only by the betting RPC functions below.';

-- ============================================================
-- bet_markets — one betting line per scheduled match. 1:1 with
-- scheduled_matches, created separately (not automatically) so a
-- casual scheduled match can exist with no betting on it at all.
-- ============================================================

create table if not exists public.bet_markets (
  id                     bigint generated by default as identity primary key,
  scheduled_match_id     bigint not null references public.scheduled_matches(id) on delete cascade,
  p1                     text not null,
  p2                     text not null,
  -- decimal odds: a winning bet returns stake * odds (stake included).
  -- The admin sets these like a bookmaker's line — a heavy favourite
  -- gets something like 1.15, a heavy underdog something like 6.0.
  odds_p1                numeric not null check (odds_p1 > 1),
  odds_p2                numeric not null check (odds_p2 > 1),
  -- extra multiplier stacked on top of the winner odds for the deeper,
  -- riskier bet types. Must strictly increase with risk.
  margin_multiplier      numeric not null default 2.0 check (margin_multiplier > 1),
  exact_multiplier       numeric not null default 5.0 check (exact_multiplier > margin_multiplier),
  status                 text not null default 'open'
                           check (status in ('open','locked','resolved','void')),
  result_winner          text,
  result_sets            text,               -- "6-4, 3-6, 7-5", p1-first — same convention as matches.sets
  created_by             text,
  created_at             timestamptz not null default now(),
  resolved_at            timestamptz,
  unique (scheduled_match_id)
);

create index if not exists bet_markets_status_idx on public.bet_markets (status);

comment on table public.bet_markets is
  'One betting line per scheduled match, opened by an admin with odds they choose. '
  'No Elo or rating input anywhere here — the admin is the house and sets the price.';

-- ============================================================
-- bets — one wager. Escrowed at placement (stake leaves the
-- bettor's wallet immediately), then either refunded (rejected /
-- voided), paid out (won), or forfeited (lost) — never adjusted by
-- the client, only by the RPCs.
-- ============================================================

create table if not exists public.bets (
  id                 bigint generated by default as identity primary key,
  market_id          bigint not null references public.bet_markets(id) on delete cascade,
  bettor_key         text not null,
  bettor_name        text not null,
  bet_type           text not null check (bet_type in ('winner','margin','exact_score')),
  pick_winner        text not null,          -- who this bet says wins
  pick_margin        text,                   -- e.g. '2-0' — required for bet_type='margin'
  pick_sets          text,                   -- e.g. '6-4, 6-3' — required for bet_type='exact_score'
  stake              integer not null check (stake > 0),
  odds               numeric not null,       -- final locked-in multiplier (winner odds x type multiplier)
  potential_payout    integer not null,
  status             text not null default 'pending'
                        check (status in ('pending','accepted','rejected','won','lost','void','cancelled')),
  admin_note         text,
  created_at         timestamptz not null default now(),
  decided_at         timestamptz,
  decided_by         text
);

create index if not exists bets_market_idx  on public.bets (market_id);
create index if not exists bets_bettor_idx  on public.bets (bettor_key);
create index if not exists bets_status_idx  on public.bets (status);

comment on table public.bets is
  'One wager against a bet_markets line. Stake is escrowed out of the wallet at '
  'placement; status moves pending -> accepted/rejected, then (for accepted) -> won/lost/void.';

-- ============================================================
-- Row level security — read is public (same posture as the rest of
-- this app), writes are closed at the table level. All mutation
-- goes through the SECURITY DEFINER functions below, which is the
-- only place balances actually move.
-- ============================================================

alter table public.wallets      enable row level security;
alter table public.bet_markets  enable row level security;
alter table public.bets         enable row level security;

drop policy if exists wallets_read      on public.wallets;
drop policy if exists bet_markets_read  on public.bet_markets;
drop policy if exists bets_read         on public.bets;
create policy wallets_read      on public.wallets      for select using (true);
create policy bet_markets_read  on public.bet_markets  for select using (true);
create policy bets_read         on public.bets         for select using (true);

-- ============================================================
-- ensure_wallet(name) — give a name its starting 300 FC exactly
-- once. Called from the app right after a display name is chosen
-- (afterIdentityChange) or a roster profile is claimed. Idempotent:
-- calling it again for the same name (case/whitespace-insensitive)
-- never resets or touches the balance.
-- ============================================================

create or replace function public.ensure_wallet(p_name text)
returns public.wallets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key  text := lower(trim(p_name));
  v_row  public.wallets;
begin
  if v_key = '' then
    raise exception 'name required';
  end if;

  insert into public.wallets (name_key, name)
  values (v_key, trim(p_name))
  on conflict (name_key) do update
    set name = excluded.name  -- keep the casing fresh, balance untouched
  returning * into v_row;

  return v_row;
end;
$$;

comment on function public.ensure_wallet(text) is
  'Creates a wallet with 300 FC for a name the first time it is seen; a no-op on '
  'balance for a name that already has one. Safe to call on every identity change.';

grant execute on function public.ensure_wallet(text) to anon, authenticated;

-- ============================================================
-- open_bet_market(...) — admin opens (or re-prices, while still
-- open) a betting line on a scheduled match.
-- ============================================================

create or replace function public.open_bet_market(
  p_scheduled_match_id bigint,
  p_odds_p1            numeric,
  p_odds_p2            numeric,
  p_margin_multiplier  numeric default 2.0,
  p_exact_multiplier   numeric default 5.0
) returns public.bet_markets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sched public.scheduled_matches;
  v_row   public.bet_markets;
  v_actor text;
begin
  if not public.is_admin() then
    raise exception 'admin only';
  end if;
  if p_odds_p1 <= 1 or p_odds_p2 <= 1 then
    raise exception 'odds must be greater than 1';
  end if;
  if p_margin_multiplier <= 1 then
    raise exception 'margin multiplier must be greater than 1';
  end if;
  if p_exact_multiplier <= p_margin_multiplier then
    raise exception 'exact-score multiplier must be greater than the margin multiplier';
  end if;

  select * into v_sched from public.scheduled_matches where id = p_scheduled_match_id;
  if v_sched is null then
    raise exception 'scheduled match not found';
  end if;

  v_actor := coalesce(auth.jwt() ->> 'email', 'admin');

  insert into public.bet_markets (scheduled_match_id, p1, p2, odds_p1, odds_p2,
                                   margin_multiplier, exact_multiplier, created_by)
  values (p_scheduled_match_id, v_sched.p1, v_sched.p2, p_odds_p1, p_odds_p2,
          p_margin_multiplier, p_exact_multiplier, v_actor)
  on conflict (scheduled_match_id) do update
    set odds_p1           = excluded.odds_p1,
        odds_p2           = excluded.odds_p2,
        margin_multiplier = excluded.margin_multiplier,
        exact_multiplier  = excluded.exact_multiplier
  -- only a still-open market may be re-priced; the WHERE clause on a
  -- DO UPDATE simply skips the update (no row, nothing thrown) when it's
  -- false, which is what lets the "already resolved" case below fire
  where bet_markets.status = 'open'
  returning * into v_row;

  if v_row is null then
    select * into v_row from public.bet_markets where scheduled_match_id = p_scheduled_match_id;
    raise exception 'market is % — re-price is only allowed while open', v_row.status;
  end if;

  return v_row;
end;
$$;

comment on function public.open_bet_market(bigint, numeric, numeric, numeric, numeric) is
  'Admin only. Opens a betting line on a scheduled match with admin-chosen decimal '
  'odds, or re-prices one that is still open. No Elo/rating input.';

grant execute on function public.open_bet_market(bigint, numeric, numeric, numeric, numeric) to authenticated;

-- ============================================================
-- set_bet_market_status(...) — admin locks (stops new bets ahead of
-- the match) or voids (cancels the whole market and refunds
-- everyone) a market.
-- ============================================================

create or replace function public.set_bet_market_status(
  p_market_id bigint,
  p_status    text
) returns public.bet_markets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.bet_markets;
  v_bet record;
begin
  if not public.is_admin() then
    raise exception 'admin only';
  end if;
  if p_status not in ('open','locked','void') then
    raise exception 'invalid status';
  end if;

  select * into v_row from public.bet_markets where id = p_market_id for update;
  if v_row is null then raise exception 'market not found'; end if;
  if v_row.status = 'resolved' then raise exception 'market already resolved'; end if;
  if v_row.status = 'void' then raise exception 'market already void'; end if;

  if p_status = 'void' then
    -- refund every escrowed bet (pending or accepted) — the house never
    -- delivered a match to bet on, so nobody's stake is at risk
    for v_bet in select * from public.bets
                 where market_id = p_market_id and status in ('pending','accepted')
    loop
      update public.wallets set balance = balance + v_bet.stake, updated_at = now()
        where name_key = v_bet.bettor_key;
      update public.bets set status = 'void', decided_at = now() where id = v_bet.id;
    end loop;
  end if;

  update public.bet_markets set status = p_status where id = p_market_id
  returning * into v_row;
  return v_row;
end;
$$;

comment on function public.set_bet_market_status(bigint, text) is
  'Admin only. Lock stops new bets; void cancels the market and refunds every '
  'escrowed stake on it.';

grant execute on function public.set_bet_market_status(bigint, text) to authenticated;

-- ============================================================
-- place_bet(...) — escrow a stake and record a wager.
-- Trusts the caller's name the same way the rest of this app trusts
-- myName() for posts/comments/challenges — there is no per-user auth
-- for the free-text identity path here, only for admins.
-- ============================================================

create or replace function public.place_bet(
  p_market_id  bigint,
  p_name       text,
  p_bet_type   text,
  p_pick_winner text,
  p_pick_margin text,
  p_pick_sets   text,
  p_stake      integer
) returns public.bets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key    text := lower(trim(p_name));
  v_market public.bet_markets;
  v_wallet public.wallets;
  v_base   numeric;
  v_mult   numeric;
  v_row    public.bets;
begin
  if v_key = '' then raise exception 'name required'; end if;
  if p_stake is null or p_stake <= 0 then raise exception 'stake must be positive'; end if;
  if p_bet_type not in ('winner','margin','exact_score') then raise exception 'invalid bet type'; end if;

  select * into v_market from public.bet_markets where id = p_market_id for update;
  if v_market is null then raise exception 'market not found'; end if;
  if v_market.status <> 'open' then raise exception 'betting is % on this match', v_market.status; end if;

  if lower(trim(p_pick_winner)) = lower(v_market.p1) then
    v_base := v_market.odds_p1;
  elsif lower(trim(p_pick_winner)) = lower(v_market.p2) then
    v_base := v_market.odds_p2;
  else
    raise exception 'pick must be % or %', v_market.p1, v_market.p2;
  end if;

  if p_bet_type = 'winner' then
    v_mult := 1;
  elsif p_bet_type = 'margin' then
    if p_pick_margin is null or trim(p_pick_margin) = '' then
      raise exception 'margin pick required, e.g. 2-0';
    end if;
    v_mult := v_market.margin_multiplier;
  else
    if p_pick_sets is null or trim(p_pick_sets) = '' then
      raise exception 'exact set scores required, e.g. 6-4, 6-3';
    end if;
    v_mult := v_market.exact_multiplier;
  end if;

  -- ensure_wallet() should already have run for any real user, but a
  -- missing wallet here (never happens in the app's own flow, but the
  -- RPC has to be safe on its own) gets one rather than failing to bet
  insert into public.wallets (name_key, name) values (v_key, trim(p_name))
    on conflict (name_key) do nothing;

  select * into v_wallet from public.wallets where name_key = v_key for update;
  if v_wallet.balance < p_stake then
    raise exception 'insufficient balance: have % FC, need % FC', v_wallet.balance, p_stake;
  end if;

  update public.wallets set balance = balance - p_stake, updated_at = now()
    where name_key = v_key;

  insert into public.bets (market_id, bettor_key, bettor_name, bet_type,
                            pick_winner, pick_margin, pick_sets, stake, odds, potential_payout)
  values (p_market_id, v_key, trim(p_name), p_bet_type,
          trim(p_pick_winner), nullif(trim(coalesce(p_pick_margin,'')),''),
          nullif(trim(coalesce(p_pick_sets,'')),''),
          p_stake, v_base * v_mult, round(p_stake * v_base * v_mult))
  returning * into v_row;

  return v_row;
end;
$$;

comment on function public.place_bet(bigint, text, text, text, text, text, integer) is
  'Escrows the stake out of the bettor''s wallet and records a pending wager. '
  'Odds are locked in at placement time from the market''s current price.';

grant execute on function public.place_bet(bigint, text, text, text, text, text, integer) to anon, authenticated;

-- ============================================================
-- admin_decide_bet(...) — the house reviews a pending bet.
-- ============================================================

create or replace function public.admin_decide_bet(
  p_bet_id bigint,
  p_accept boolean,
  p_note   text default null
) returns public.bets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_bet   public.bets;
  v_actor text;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;

  select * into v_bet from public.bets where id = p_bet_id for update;
  if v_bet is null then raise exception 'bet not found'; end if;
  if v_bet.status <> 'pending' then raise exception 'bet already %', v_bet.status; end if;

  v_actor := coalesce(auth.jwt() ->> 'email', 'admin');

  if not p_accept then
    update public.wallets set balance = balance + v_bet.stake, updated_at = now()
      where name_key = v_bet.bettor_key;
  end if;

  update public.bets
     set status = case when p_accept then 'accepted' else 'rejected' end,
         admin_note = p_note, decided_at = now(), decided_by = v_actor
   where id = p_bet_id
  returning * into v_bet;

  return v_bet;
end;
$$;

comment on function public.admin_decide_bet(bigint, boolean, text) is
  'Admin only. Accepts a pending bet (stays escrowed) or rejects it (refunds the stake).';

grant execute on function public.admin_decide_bet(bigint, boolean, text) to authenticated;

-- ============================================================
-- resolve_bet_market(...) — admin enters the real result once the
-- match is played; every accepted bet on the market settles itself,
-- and any bet the house never got round to reviewing is voided and
-- refunded rather than left to rot as a pending row on a finished
-- match.
-- ============================================================

create or replace function public.resolve_bet_market(
  p_market_id bigint,
  p_winner    text,
  p_sets      text
) returns public.bet_markets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_market       public.bet_markets;
  v_bet          record;
  v_pair         text;
  v_a            int;
  v_b            int;
  v_p1_sets      int := 0;
  v_p2_sets      int := 0;
  v_actual_margin text;
  v_won          boolean;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;

  select * into v_market from public.bet_markets where id = p_market_id for update;
  if v_market is null then raise exception 'market not found'; end if;
  if v_market.status = 'resolved' then raise exception 'already resolved'; end if;
  if v_market.status = 'void' then raise exception 'market was voided'; end if;

  if lower(trim(p_winner)) not in (lower(v_market.p1), lower(v_market.p2)) then
    raise exception 'winner must be % or %', v_market.p1, v_market.p2;
  end if;
  if p_sets is null or trim(p_sets) = '' then
    raise exception 'set scores required, e.g. 6-4, 3-6, 7-5';
  end if;

  -- tally sets won by each side from "a-b, a-b, ..." (p1-first, same
  -- convention as matches.sets everywhere else in this app)
  foreach v_pair in array string_to_array(p_sets, ',')
  loop
    v_pair := trim(v_pair);
    continue when v_pair = '';
    v_a := split_part(v_pair, '-', 1)::int;
    v_b := split_part(v_pair, '-', 2)::int;
    if v_a > v_b then v_p1_sets := v_p1_sets + 1;
    elsif v_b > v_a then v_p2_sets := v_p2_sets + 1;
    end if;
  end loop;

  if lower(trim(p_winner)) = lower(v_market.p1) then
    v_actual_margin := v_p1_sets || '-' || v_p2_sets;
  else
    v_actual_margin := v_p2_sets || '-' || v_p1_sets;
  end if;

  for v_bet in select * from public.bets
               where market_id = p_market_id and status in ('pending','accepted')
  loop
    if v_bet.status = 'pending' then
      -- the house never reviewed it before the match happened — refund,
      -- don't leave it hanging and don't let it win or lose unreviewed
      update public.wallets set balance = balance + v_bet.stake, updated_at = now()
        where name_key = v_bet.bettor_key;
      update public.bets set status = 'void', decided_at = now() where id = v_bet.id;
      continue;
    end if;

    v_won := lower(v_bet.pick_winner) = lower(trim(p_winner));
    if v_won and v_bet.bet_type = 'margin' then
      v_won := replace(v_bet.pick_margin, ' ', '') = replace(v_actual_margin, ' ', '');
    elsif v_won and v_bet.bet_type = 'exact_score' then
      v_won := replace(lower(v_bet.pick_sets), ' ', '') = replace(lower(trim(p_sets)), ' ', '');
    end if;

    if v_won then
      update public.wallets set balance = balance + v_bet.potential_payout, updated_at = now()
        where name_key = v_bet.bettor_key;
      update public.bets set status = 'won', decided_at = now() where id = v_bet.id;
    else
      update public.bets set status = 'lost', decided_at = now() where id = v_bet.id;
    end if;
  end loop;

  update public.bet_markets
     set status = 'resolved', result_winner = trim(p_winner), result_sets = trim(p_sets), resolved_at = now()
   where id = p_market_id
  returning * into v_market;

  return v_market;
end;
$$;

comment on function public.resolve_bet_market(bigint, text, text) is
  'Admin only. Records the real result and settles every accepted bet on the '
  'market; any bet still pending gets voided and refunded rather than settled blind.';

grant execute on function public.resolve_bet_market(bigint, text, text) to authenticated;

-- ============================================================
-- Realtime — balances and market/bet status should update live for
-- everyone watching, same as the rest of the app's tables.
-- ============================================================

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'wallets'
  ) then
    alter publication supabase_realtime add table public.wallets;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'bet_markets'
  ) then
    alter publication supabase_realtime add table public.bet_markets;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'bets'
  ) then
    alter publication supabase_realtime add table public.bets;
  end if;
end $$;
