-- The Kit: rackets and string jobs.
--
-- Both tables are optional. Without them the Kit screen explains what it
-- would do and points here; nothing else in the app reads either one, so a
-- deployment that never runs this file is not missing anything else.
--
-- What the app does NOT store here is the part everybody expects to have to
-- keep up to date: how much tennis has been played on a bed. That is derived
-- from `matches` and `practice_log`, which are already being written for
-- other reasons — a point-tracked match carries the ref's own start and end
-- instants inside `rallies`, every other approved match has a scoreline, and
-- the casual-session form already asks for minutes per player. So the only
-- thing anybody types here is the stringing itself.
--
-- Run this in the Supabase SQL editor.

create table if not exists public.rackets (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  owner       text not null,
  name        text not null,
  -- free text, for telling two of the same frame apart: "the one with the
  -- blue grip". Deliberately not a model/spec field — nobody would fill it in
  label       text
);

create table if not exists public.string_jobs (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  owner        text not null,
  -- nullable on purpose: a job recorded before the frame was added, or on a
  -- deployment with no `rackets` table, is still a real string job. The FK is
  -- ON DELETE SET NULL for the same reason — removing a frame must not delete
  -- the history of what was strung in it.
  racket_id    bigint references public.rackets(id) on delete set null,
  -- one of: poly, multi, syn, gut, hybrid, kevlar. Kept as text rather than
  -- an enum so adding a material to KIT_STRINGS needs no migration; an
  -- unknown value falls back to the default in the app.
  material     text not null default 'poly',
  tension      numeric not null,
  -- for a hybrid strung at two tensions. Null means the same as `tension`.
  tension_cross numeric,
  main_string  text,
  cross_string text,
  gauge        text,
  notes        text,
  strung_at    timestamptz not null default now(),
  -- when the bed came out. This is what stops a retired job from accruing
  -- hours forever, and it is the only way "it lasted 31 days" is knowable
  -- later, so cutting a bed out records a date rather than deleting the row.
  removed_at   timestamptz
);

create index if not exists rackets_owner_idx      on public.rackets (owner);
create index if not exists string_jobs_owner_idx  on public.string_jobs (owner);
create index if not exists string_jobs_racket_idx on public.string_jobs (racket_id);
create index if not exists string_jobs_strung_idx on public.string_jobs (strung_at desc);

alter table public.rackets      enable row level security;
alter table public.string_jobs  enable row level security;

-- Same posture as the rest of the league's tables: everything is readable by
-- everybody, because the whole point is comparing bags, and writes are open
-- to the anon key the way the practice log and the match report already are.
-- If this project has tightened those, tighten these to match rather than
-- leaving one table with a different rule from its neighbours.
drop policy if exists "rackets are public"      on public.rackets;
drop policy if exists "string jobs are public"  on public.string_jobs;
create policy "rackets are public"     on public.rackets     for select using (true);
create policy "string jobs are public" on public.string_jobs for select using (true);

drop policy if exists "anyone can add a racket"     on public.rackets;
drop policy if exists "anyone can remove a racket"  on public.rackets;
drop policy if exists "anyone can log a stringing"  on public.string_jobs;
drop policy if exists "anyone can cut a bed out"    on public.string_jobs;
create policy "anyone can add a racket"    on public.rackets     for insert with check (true);
create policy "anyone can remove a racket" on public.rackets     for delete using (true);
create policy "anyone can log a stringing" on public.string_jobs for insert with check (true);
create policy "anyone can cut a bed out"   on public.string_jobs for update using (true) with check (true);
