-- ============================================================
-- kit.min.sql — the same migration as kit.sql with the
-- explanation stripped out, for pasting.
--
-- Use this one when you are copying into the Supabase SQL editor
-- from a phone, or when you just want the statements. Read
-- kit.sql for WHY any of it is shaped the way it is — in
-- particular why the hours are NOT stored here; the reasoning
-- lives there and only there.
--
-- PASTE THIS FILE ON ITS OWN. Supabase runs an editor tab as one
-- transaction, so one error anywhere — including a harmless
-- "already exists" from an unrelated script pasted above it —
-- rolls back everything after it, and you are left with none of
-- these tables and no obvious sign why.
--
-- It assumes nothing. Every statement is guarded, so running it
-- twice is safe, and the app works without it (the Kit screen
-- says which table is missing rather than showing an empty bag).
-- ============================================================

create table if not exists public.rackets (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  owner       text not null,
  name        text not null,
  label       text
);

create table if not exists public.string_jobs (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  owner        text not null,
  racket_id    bigint references public.rackets(id) on delete set null,
  material     text not null default 'poly',
  tension      numeric not null,
  tension_cross numeric,
  main_string  text,
  cross_string text,
  gauge        text,
  notes        text,
  strung_at    timestamptz not null default now(),
  removed_at   timestamptz
);

create index if not exists rackets_owner_idx      on public.rackets (owner);
create index if not exists string_jobs_owner_idx  on public.string_jobs (owner);
create index if not exists string_jobs_racket_idx on public.string_jobs (racket_id);
create index if not exists string_jobs_strung_idx on public.string_jobs (strung_at desc);

alter table public.rackets      enable row level security;
alter table public.string_jobs  enable row level security;

drop policy if exists "rackets are public"      on public.rackets;
drop policy if exists "string jobs are public"  on public.string_jobs;
create policy "rackets are public"     on public.rackets     for select using (true);
create policy "string jobs are public" on public.string_jobs for select using (true);

drop policy if exists "anyone can add a racket"     on public.rackets;
drop policy if exists "anyone can remove a racket"  on public.rackets;
drop policy if exists "anyone can log a stringing"  on public.string_jobs;
drop policy if exists "anyone can cut a bed out"    on public.string_jobs;
create policy "anyone can add a racket"    on public.rackets     for insert with check (true);
create policy "anyone can remove a racket" on public.rackets     for delete using (true);
create policy "anyone can log a stringing" on public.string_jobs for insert with check (true);
create policy "anyone can cut a bed out"   on public.string_jobs for update using (true) with check (true);
